### ISSUE TITLE
Waterbeach station missing 

### ISSUE THREAD

**Issue by richardwilliamson** [anisotropi4/kingfisher#1]
Waterbeach seems to be missing unless I’m being dumb?

**Comment by alasdairrae** [comment]
They are all there but the two column layout might make finding some of them less intuitive for some, e.g. on mobile but here's Waterbeach 

https://github.com/anisotropi4/kingfisher/blob/main/image/W/WBC-rail.png

**Comment by richardwilliamson** [comment]
Oh apologies. It was indeed me being dumb. I looked 3 times!!

**Comment by alasdairrae** [comment]
Well I can't find the butter in the fridge when it's right in front of my face so I think you get a free pass on this!

**Comment by anisotropi4** [comment]
Fixed as required.
