### ISSUE TITLE
Missing stations:- Bentham line

### ISSUE THREAD

**Issue by Jesdene** [anisotropi4/kingfisher#2]
Bentham and Carnforth missing

**Comment by benabineri** [comment]
They're there - https://github.com/anisotropi4/kingfisher/blob/main/station.md is laid out in 2 columns and they're both in the right column which I suspect isn't easy to spot on mobile.

**Comment by Jesdene** [comment]
CheersJohnSent from my iPhoneOn 3 Jan 2024, at 10:46, Ben Abineri ***@***.***> wrote:﻿
They're there - https://github.com/anisotropi4/kingfisher/blob/main/station.md is laid out in 2 columns and they're both in the right column which I suspect isn't easy to spot on mobile.

**Comment by anisotropi4** [comment]
@Jesdene would you be ok if I close this as fixed?

**Comment by Jesdene** [comment]
Yes, that’s fine, thanksSent from my iPhoneOn 3 Jan 2024, at 19:12, Will Deakin ***@***.***> wrote:﻿
@Jesdene would you be ok if I close this as fixed?

**Comment by anisotropi4** [comment]
Closed with thanks
