### ISSUE TITLE
Happy to help with hosting images

### ISSUE THREAD

**Issue by srinify** [anisotropi4/kingfisher#5]
This repo is awesome, great work curating these flow images! Has GitHub disabled Git LFS for you in this repo? 

I work at XetHub and we offer a similar experience to LFS but we have no limits or costs for public repos. Here's an example of a repo with gigabytes of ML model files that we mirrored & hosted: https://github.com/xetdata/onnx-models

With our browser extension, people can open files in GitHub's UI and see links to XetHub rendered images. Quick example:

https://github.com/anisotropi4/kingfisher/assets/801507/29d3d316-f69f-424a-ac38-92d03ca7a290

**Comment by srinify** [comment]
@anisotropi4 saw the thumbs up. Would you like me to fork the repo and set this up and send you the link? Or I can show you how to do it here itself, open to whatever.

**Comment by anisotropi4** [comment]
@srinify If you would, that would be amazing. I have got the site back by removing LFS but I don't know for how long. Having a plan B would be great.

I have also set up a XetHub account that I would very much be interested in using in the future but I could do with a banker for today. You help here is very much appreciated.

**Comment by srinify** [comment]
Sounds good @anisotropi4 I"ll set it up and circle back shortly!

**Comment by anisotropi4** [comment]
I have got it working and the latest GeoGPKG files are up on xethub [here](https://xethub.com/anisotropi4/kingfisher/). Closed as complete. Thanks for sharing this.

**Comment by srinify** [comment]
Awesome! 🎉 @anisotropi4
