### ISSUE TITLE
Link to Data Missing

### ISSUE THREAD

**Issue by djaychela** [anisotropi4/kingfisher#6]
Hi

To get around the LFS issue and inability to see the images, I forked and downloaded the repo, and it wants to run, but there's no link I can see to the data.  Could you point me in the right direction to get the data so I can run this?

Thanks

**Comment by anisotropi4** [comment]
Hi

You got me. I've not published the script that was used to generate the data nor the base data, and links. I was planning on getting this sorted this week and pushing this to GitHub on the weekend. FWIW this was very much a post-Boxing Day holiday project not my day job.

I'm going to see how I can fix the hosting tonight, having just got in from meetings, and get on to cleaning up the code and instructions over the next few days.

Hope that helps.

**Comment by anisotropi4** [comment]
I've just had a go a updating and posting the scripts with some minimal instructions in the README.md if you're still interested in having a look. It is very much *beta development* code as I hacked it over a few days over the holiday break. However, if you want to give it a go it should work. 

However, I've not run it to completion as it takes quite a long time to execute on my old kit (5-6h). So let's see where we are in the morning.

**Comment by djaychela** [comment]
Hi Will.  Thanks for that - I will give it a go over the weekend, I'll be running it on an M1 Max macbook so I'll let you know how it goes!
